"""Single source of truth for the colordoc palette.

Every class in the colordoc schema is one flat RGB fill, so this table *is* the
classification logic. Both sides of the tool read it from here:

- ``generate_doc.py`` paints pages with these colors,
- ``palette.hpp`` (generated by :func:`write_header`) is what the C++ classify
  functions compare against.

Keeping it in Python and generating the header follows the same precedent as
the rest of the project: Python owns the schema, and the native code is
generated from it (see ``.github/copilot-instructions.md``).
"""

from pathlib import Path
import logging

logger = logging.getLogger(__name__)

RGB = tuple[int, int, int]

#: class name -> RGB fill. Values are deliberately far apart in every channel so
#: that "which class is this page" is never ambiguous - a misclassification is a
#: classifier bug, never a palette ambiguity.
PALETTE: dict[str, RGB] = {
    "section": (0xC8, 0x1E, 0x1E),     # red
    "subsection": (0x1E, 0x8C, 0x3C),  # green
    "figure": (0x1E, 0x4A, 0xC8),      # blue
    "caption": (0xE0, 0xA8, 0x14),     # amber
}

#: Painted on the blank page that follows a section. Matches no class, so every
#: classify function must fail on it - that is what makes the BlankAfter
#: override observable.
BLANK: RGB = (0xFF, 0xFF, 0xFF)

#: Per-channel slack when comparing a rendered pixel to a palette entry. Flat
#: fills round-trip exactly, so this only absorbs rasteriser rounding; it is far
#: smaller than the distance between any two palette entries.
TOLERANCE: int = 6

HEADER_NAME = "palette.hpp"


def min_channel_distance() -> int:
    """Smallest per-channel gap between any two paintable colors.

    Guards the invariant the whole tool rests on: no two colors may be within
    ``TOLERANCE`` of each other, or classification stops being objective.
    """
    colors = list(PALETTE.values()) + [BLANK]
    best = 255
    for i, a in enumerate(colors):
        for b in colors[i + 1:]:
            best = min(best, max(abs(x - y) for x, y in zip(a, b)))
    return best


def validate() -> None:
    gap = min_channel_distance()
    if gap <= TOLERANCE:
        raise RuntimeError(
            f"palette is ambiguous: closest pair differs by {gap} in its widest "
            f"channel, which is within TOLERANCE={TOLERANCE}"
        )


def _const_name(class_name: str) -> str:
    return f"{class_name.upper()}_COLOR"


def write_header(path: Path) -> None:
    """Generate ``palette.hpp`` next to the user C++ sources.

    The write is skipped when the contents are unchanged so that re-running the
    tool does not force a needless C++ rebuild.
    """
    validate()

    entries = "\n".join(
        f"inline constexpr Rgb {_const_name(name):<18} = {{{r:>3}, {g:>3}, {b:>3}}};"
        for name, (r, g, b) in PALETTE.items()
    )

    contents = f"""// GENERATED by tools/colordoc/palette.py - do not edit by hand.
#pragma once

#include <cstdint>

struct Rgb {{
  uint8_t r;
  uint8_t g;
  uint8_t b;
}};

/// Per-channel slack when matching a rendered pixel against a palette entry.
inline constexpr int COLOR_TOLERANCE = {TOLERANCE};

{entries}

/// The fill of the blank page that follows a section. Matches no class.
inline constexpr Rgb {_const_name('blank'):<18} = {{{BLANK[0]:>3}, {BLANK[1]:>3}, {BLANK[2]:>3}}};
"""

    if path.exists() and path.read_text(encoding="utf-8") == contents:
        logger.debug("palette header at %s already up to date", path)
        return

    path.write_text(contents, encoding="utf-8")
    logger.info("wrote palette header -> %s", path)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    write_header(Path(__file__).parent / HEADER_NAME)
