from pathlib import Path
from weakref import ref
from pdf_classifier.rust_class_serializer import RustClassSerializer
from pdf_classifier.object import Object
import pytest
import tempfile

# ! generated by AI, asserts that generated file matches original syntax 
# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_example_objects() -> list[Object]:
    """
    Mirrors examples/main.py without touching the global OBJECTS list.
    Produces: unknown(0), chapter(1), subchapter(2), diagram(3), datatable(4)
    """
    unknown = Object("unknown", "UNKNOWN_classify", "UNKNOWN_extract")
    chapter = Object("chapter", "classify", "extract", is_organizational=True)
    subchapter = Object("subchapter", "classify", "extract", is_organizational=True)
    diagram = Object("diagram", "classify", "extract")
    datatable = Object("datatable", "classify", "extract")

    # chapter → subchapter
    chapter.children.append(ref(subchapter))
    # subchapter → diagram, datatable
    subchapter.children.append(ref(diagram))
    subchapter.children.append(ref(datatable))
    # diagram ↔ datatable pair
    diagram.pair = (ref(datatable), 1)
    datatable.pair = (ref(diagram), 2)

    return [unknown, chapter, subchapter, diagram, datatable]


def _serializer(objects: list[Object] | None = None) -> RustClassSerializer:
    if objects is None:
        objects = _make_example_objects()
    return RustClassSerializer(objects, Path(tempfile.gettempdir()))


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def objs() -> list[Object]:
    return _make_example_objects()


@pytest.fixture
def ser(objs: list[Object]) -> RustClassSerializer:
    return RustClassSerializer(objs, Path(tempfile.gettempdir()))


# ---------------------------------------------------------------------------
# OBJECT_COUNT constant
# ---------------------------------------------------------------------------

class TestObjectCountConst:
    def test_count_matches_object_list_length(self, ser: RustClassSerializer, objs: list[Object]):
        ser._object_count_const()
        assert f"pub const OBJECT_COUNT: u8 = {len(objs)};" in ser.data

    def test_count_value_is_five_for_example_schema(self, ser: RustClassSerializer):
        ser._object_count_const()
        assert "pub const OBJECT_COUNT: u8 = 5;" in ser.data

    def test_single_object_count(self):
        s = RustClassSerializer([Object("unknown", "", "")], Path(tempfile.gettempdir()))
        s._object_count_const()
        assert "pub const OBJECT_COUNT: u8 = 1;" in s.data


# ---------------------------------------------------------------------------
# Enum generation
# ---------------------------------------------------------------------------

class TestClassEnum:
    def test_enum_declaration_present(self, ser: RustClassSerializer):
        ser._class_enum()
        assert "pub enum KnownObject {" in ser.data

    def test_repr_u8_attribute(self, ser: RustClassSerializer):
        ser._class_enum()
        assert "#[repr(u8)]" in ser.data

    def test_derive_attributes(self, ser: RustClassSerializer):
        ser._class_enum()
        assert "Clone" in ser.data
        assert "Copy" in ser.data
        assert "Debug" in ser.data
        assert "PartialEq" in ser.data
        assert "Eq" in ser.data
        assert "Hash" in ser.data

    def test_all_variants_uppercase(self, ser: RustClassSerializer):
        ser._class_enum()
        for name in ("UNKNOWN", "CHAPTER", "SUBCHAPTER", "DIAGRAM", "DATATABLE"):
            assert name in ser.data

    def test_discriminants_are_sequential(self, ser: RustClassSerializer):
        ser._class_enum()
        # Check each name=index assignment
        for i, name in enumerate(("UNKNOWN", "CHAPTER", "SUBCHAPTER", "DIAGRAM", "DATATABLE")):
            assert f"{name}= {i}" in ser.data


# ---------------------------------------------------------------------------
# has_children
# ---------------------------------------------------------------------------

class TestHasChildrenMethod:
    def test_method_signature_generated(self, ser: RustClassSerializer):
        ser._begin_impl_block()
        ser._has_children_method()
        ser._end_impl_block()
        assert "pub const fn has_children(&self) -> bool {" in ser.data

    def test_objects_with_children_return_true(self, ser: RustClassSerializer):
        ser._begin_impl_block()
        ser._has_children_method()
        ser._end_impl_block()
        assert "KnownObject::CHAPTER => true" in ser.data
        assert "KnownObject::SUBCHAPTER => true" in ser.data

    def test_leaf_objects_return_false(self, ser: RustClassSerializer):
        ser._begin_impl_block()
        ser._has_children_method()
        ser._end_impl_block()
        assert "KnownObject::UNKNOWN => false" in ser.data
        assert "KnownObject::DIAGRAM => false" in ser.data
        assert "KnownObject::DATATABLE => false" in ser.data


# ---------------------------------------------------------------------------
# has_pair
# ---------------------------------------------------------------------------

class TestHasPairMethod:
    def test_method_signature_generated(self, ser: RustClassSerializer):
        ser._begin_impl_block()
        ser._has_pair_method()
        ser._end_impl_block()
        assert "pub const fn has_pair(&self) -> bool {" in ser.data

    def test_paired_objects_return_true(self, ser: RustClassSerializer):
        ser._begin_impl_block()
        ser._has_pair_method()
        ser._end_impl_block()
        assert "KnownObject::DIAGRAM => true" in ser.data
        assert "KnownObject::DATATABLE => true" in ser.data

    def test_unpaired_objects_return_false(self, ser: RustClassSerializer):
        ser._begin_impl_block()
        ser._has_pair_method()
        ser._end_impl_block()
        assert "KnownObject::UNKNOWN => false" in ser.data
        assert "KnownObject::CHAPTER => false" in ser.data
        assert "KnownObject::SUBCHAPTER => false" in ser.data


# ---------------------------------------------------------------------------
# is_first_in_pair
# ---------------------------------------------------------------------------

class TestIsFirstInPairMethod:
    def test_method_signature_generated(self, ser: RustClassSerializer):
        ser._begin_impl_block()
        ser._is_first_in_pair_method()
        ser._end_impl_block()
        assert "pub const fn is_first_in_pair(&self) -> bool {" in ser.data

    def test_diagram_is_first(self, ser: RustClassSerializer):
        ser._begin_impl_block()
        ser._is_first_in_pair_method()
        ser._end_impl_block()
        assert "KnownObject::DIAGRAM => true" in ser.data

    def test_only_first_element_is_true(self, ser: RustClassSerializer):
        ser._begin_impl_block()
        ser._is_first_in_pair_method()
        ser._end_impl_block()
        assert "KnownObject::DATATABLE => false" in ser.data
        assert "KnownObject::UNKNOWN => false" in ser.data
        assert "KnownObject::CHAPTER => false" in ser.data
        assert "KnownObject::SUBCHAPTER => false" in ser.data


# ---------------------------------------------------------------------------
# is_second_in_pair
# ---------------------------------------------------------------------------

class TestIsSecondInPairMethod:
    def test_method_signature_generated(self, ser: RustClassSerializer):
        ser._begin_impl_block()
        ser._is_second_in_pair_method()
        ser._end_impl_block()
        assert "pub const fn is_second_in_pair(&self) -> bool {" in ser.data

    def test_datatable_is_second(self, ser: RustClassSerializer):
        ser._begin_impl_block()
        ser._is_second_in_pair_method()
        ser._end_impl_block()
        assert "KnownObject::DATATABLE => true" in ser.data

    def test_only_second_element_is_true(self, ser: RustClassSerializer):
        ser._begin_impl_block()
        ser._is_second_in_pair_method()
        ser._end_impl_block()
        assert "KnownObject::DIAGRAM => false" in ser.data
        assert "KnownObject::UNKNOWN => false" in ser.data
        assert "KnownObject::CHAPTER => false" in ser.data
        assert "KnownObject::SUBCHAPTER => false" in ser.data


# ---------------------------------------------------------------------------
# ToString impl
# ---------------------------------------------------------------------------

class TestToStringImpl:
    def test_impl_block_present(self, ser: RustClassSerializer):
        ser._to_str_impl()
        assert "impl ToString for KnownObject {" in ser.data

    def test_fn_signature(self, ser: RustClassSerializer):
        ser._to_str_impl()
        assert "fn to_string(&self) -> String {" in ser.data

    def test_all_variants_map_to_lowercase_name(self, ser: RustClassSerializer):
        ser._to_str_impl()
        for name in ("unknown", "chapter", "subchapter", "diagram", "datatable"):
            assert f'"{name}".to_string()' in ser.data

    def test_variant_names_are_uppercase_in_match_arm(self, ser: RustClassSerializer):
        ser._to_str_impl()
        for name in ("UNKNOWN", "CHAPTER", "SUBCHAPTER", "DIAGRAM", "DATATABLE"):
            assert f"KnownObject::{name}" in ser.data


# ---------------------------------------------------------------------------
# ObjectCastError enum
# ---------------------------------------------------------------------------

class TestObjCastErrEnum:
    def test_error_enum_declared(self, ser: RustClassSerializer):
        ser._obj_cast_err_enum()
        assert "pub enum ObjectCastError {" in ser.data

    def test_thiserror_derive(self, ser: RustClassSerializer):
        ser._obj_cast_err_enum()
        assert "thiserror::Error" in ser.data

    def test_string_cast_error_variant(self, ser: RustClassSerializer):
        ser._obj_cast_err_enum()
        assert "StringCastError(String)" in ser.data

    def test_uint_cast_error_variant(self, ser: RustClassSerializer):
        ser._obj_cast_err_enum()
        assert "UIntCastError(u8)" in ser.data


# ---------------------------------------------------------------------------
# TryFrom<&str> impl
# ---------------------------------------------------------------------------

class TestFromStrImpl:
    def test_impl_block_present(self, ser: RustClassSerializer):
        ser._from_str_impl()
        assert "impl TryFrom<&str> for KnownObject {" in ser.data

    def test_error_type_declared(self, ser: RustClassSerializer):
        ser._from_str_impl()
        assert "type Error = ObjectCastError;" in ser.data

    def test_all_lowercase_names_present(self, ser: RustClassSerializer):
        ser._from_str_impl()
        for name in ("unknown", "chapter", "subchapter", "diagram", "datatable"):
            assert f'"{name}"' in ser.data

    def test_wildcard_arm_returns_error(self, ser: RustClassSerializer):
        ser._from_str_impl()
        assert "ObjectCastError::StringCastError" in ser.data

    def test_ok_variant_wrapping(self, ser: RustClassSerializer):
        ser._from_str_impl()
        assert "Ok(KnownObject::UNKNOWN)" in ser.data
        assert "Ok(KnownObject::CHAPTER)" in ser.data


# ---------------------------------------------------------------------------
# TryFrom<u8> impl
# ---------------------------------------------------------------------------

class TestFromU8Impl:
    def test_impl_block_present(self, ser: RustClassSerializer):
        ser._from_u8_impl()
        assert "impl TryFrom<u8> for KnownObject {" in ser.data

    def test_bounds_check_present(self, ser: RustClassSerializer):
        ser._from_u8_impl()
        assert "if value > OBJECT_COUNT {" in ser.data

    def test_uint_cast_error_on_out_of_bounds(self, ser: RustClassSerializer):
        ser._from_u8_impl()
        assert "ObjectCastError::UIntCastError(value)" in ser.data

    def test_all_discriminants_present(self, ser: RustClassSerializer):
        ser._from_u8_impl()
        for i, name in enumerate(("UNKNOWN", "CHAPTER", "SUBCHAPTER", "DIAGRAM", "DATATABLE")):
            assert f"{i} => Self::{name}" in ser.data

    def test_unreachable_arm_present(self, ser: RustClassSerializer):
        ser._from_u8_impl()
        assert "unreachable!" in ser.data


# ---------------------------------------------------------------------------
# Default impl
# ---------------------------------------------------------------------------

class TestDefaultImpl:
    def test_impl_block_present(self, ser: RustClassSerializer):
        ser._default_impl()
        assert "impl Default for KnownObject {" in ser.data

    def test_returns_unknown(self, ser: RustClassSerializer):
        ser._default_impl()
        assert "Self::UNKNOWN" in ser.data


# ---------------------------------------------------------------------------
# Into<u8> impl
# ---------------------------------------------------------------------------

class TestIntoU8Impl:
    def test_impl_block_present(self, ser: RustClassSerializer):
        ser._into_u8_impl()
        assert "impl Into<u8> for KnownObject {" in ser.data

    def test_all_discriminants_present(self, ser: RustClassSerializer):
        ser._into_u8_impl()
        for i, name in enumerate(("UNKNOWN", "CHAPTER", "SUBCHAPTER", "DIAGRAM", "DATATABLE")):
            assert f"Self::{name} => {i}" in ser.data


# ---------------------------------------------------------------------------
# Full generate() — writes to a temp dir and validates file content
# ---------------------------------------------------------------------------

class TestFullGenerate:
    def test_file_is_written(self, objs: list[Object]):
        with tempfile.TemporaryDirectory() as tmp:
            s = RustClassSerializer(objs, Path(tmp))
            s.generate()
            out = Path(tmp) / "generated_object_types.rs"
            assert out.exists()
            assert out.stat().st_size > 0

    def test_generated_content_contains_object_count(self, objs: list[Object]):
        with tempfile.TemporaryDirectory() as tmp:
            s = RustClassSerializer(objs, Path(tmp))
            s.generate()
            content = (Path(tmp) / "generated_object_types.rs").read_text()
            assert "pub const OBJECT_COUNT: u8 = 5;" in content

    def test_generated_content_contains_enum(self, objs: list[Object]):
        with tempfile.TemporaryDirectory() as tmp:
            s = RustClassSerializer(objs, Path(tmp))
            s.generate()
            content = (Path(tmp) / "generated_object_types.rs").read_text()
            assert "pub enum KnownObject {" in content

    def test_generated_content_contains_all_impls(self, objs: list[Object]):
        with tempfile.TemporaryDirectory() as tmp:
            s = RustClassSerializer(objs, Path(tmp))
            s.generate()
            content = (Path(tmp) / "generated_object_types.rs").read_text()
            assert "impl ToString for KnownObject {" in content
            assert "impl TryFrom<&str> for KnownObject {" in content
            assert "impl TryFrom<u8> for KnownObject {" in content
            assert "impl Default for KnownObject {" in content
            assert "impl Into<u8> for KnownObject {" in content

    def test_generated_content_contains_error_enum(self, objs: list[Object]):
        with tempfile.TemporaryDirectory() as tmp:
            s = RustClassSerializer(objs, Path(tmp))
            s.generate()
            content = (Path(tmp) / "generated_object_types.rs").read_text()
            assert "pub enum ObjectCastError {" in content

    def test_data_attribute_populated_after_generate(self, objs: list[Object]):
        with tempfile.TemporaryDirectory() as tmp:
            s = RustClassSerializer(objs, Path(tmp))
            s.generate()
            assert len(s.data) > 0
