from .serializer import Serializer
from .object import Object
from pathlib import Path
import textwrap
import logging

logger = logging.getLogger(__name__)

class HierarchySerializer(Serializer): 
    objects: list[Object]
    out_path: Path
    data: str
    
    def __init__(self, objects: list[Object], core_generated_module_path: Path, file_name: str = "reflected_objects.rs"): 
        self.objects = objects 
        self.out_path = core_generated_module_path / file_name
        self.data = ""
        
    def generate(self) -> None: 
        logger.info("Generating Rust hierarchy -> %s", self.out_path)
        logger.debug("Hierarchy contains %d objects", len(self.objects))
        self._append_imports()
        self._node_struct()
        self._object_list()
        self._def_table_matrix_type()
        self._children_matrix()
        self._parent_matrix()
        self._pair_matrix()
        self._independents_matrix()
        self._idx_helper_fn()
        self._is_child_helper_fn()
        self._is_parent_helper_fn()
        self._is_pair_helper_fn()
        self._is_root_helper_fn()
        self._is_independent_helper_fn()
        self._dump_data(self.out_path, self.data)
        logger.debug("Hierarchy serializer done")
    
    def _append_imports(self): 
        self.data += textwrap.dedent("""
            // This module was generated by the build.py script apart of pdf_classifier
            use super::generated_object_types::KnownObject;
            use super::generated_object_types::OBJECT_COUNT;
        """)
    
    def _node_struct(self): 
        self.data += textwrap.dedent(f"""
            #[allow(unused)]
            pub struct Node {{
                pub name: KnownObject,
                pub children: &'static [Node],
                pub pair: Option<&'static str>,
            }}
        """)
    
    def _object_list(self): 
        self.data += textwrap.dedent(f"""
            #[allow(unused)]
            pub const OBJECTS: [Node; 1] = [
                {self._get_root_obj().__serialize_to_cpp_str__()}
            ];
        """)
        
    def _def_table_matrix_type(self) -> None: 
        self.data += textwrap.dedent("""
            /// 2x2 matrix where each X, Y index is equivalent to the numeric represenitive
            /// of each [KnownObject] member
            type TableMatrix = [[bool; OBJECT_COUNT as usize]; OBJECT_COUNT as usize];
        """)
        
    def _children_matrix(self) -> None: 
        valid_children_matrix = self._build_valid_children_matrix()
        children_rows = self._format_matrix_rows(valid_children_matrix, "VALID_CHILDREN")
        self.data += self._fmt_payload([children_rows])

    def _parent_matrix(self) -> None: 
        valid_parents_matrix = self._build_valid_parents_matrix()
        parents_rows = self._format_matrix_rows(valid_parents_matrix, "VALID_PARENTS")
        self.data += self._fmt_payload([parents_rows])
    
    def _pair_matrix(self) -> None: 
        valid_pairs_matrix = self._build_valid_pairs_matrix()
        pairs_rows = self._format_matrix_rows(valid_pairs_matrix, "VALID_PAIRS")
        self.data += self._fmt_payload([pairs_rows])
        
    def _independents_matrix(self) -> None: 
        independents_array = self._build_independents_array()
        independents_str = self._format_array(independents_array, "INDEPENDENTS")
        self.data += self._fmt_payload([independents_str])
        
    def _idx_helper_fn(self) -> None: 
        self.data += textwrap.dedent(f"""
            #[inline]
            const fn idx(o: KnownObject) -> usize {{
                o as usize
            }}
        """)
        
    def _is_child_helper_fn(self) -> None: 
        self.data += textwrap.dedent(f"""
            #[inline]
            pub const fn is_child(parent: KnownObject, child: KnownObject) -> bool {{
                VALID_CHILDREN[idx(parent)][idx(child)]
            }}
        """)
        
    def _is_parent_helper_fn(self) -> None: 
        self.data += textwrap.dedent(f"""
            #[inline]
            pub const fn is_parent(parent: KnownObject, child: KnownObject) -> bool {{
                VALID_PARENTS[idx(parent)][idx(child)]
            }}
        """)
        
    def _is_pair_helper_fn(self) -> None: 
        self.data += textwrap.dedent(f"""
            #[inline]
            pub const fn is_pair(o1: KnownObject, o2: KnownObject) -> bool {{
                VALID_PAIRS[idx(o1)][idx(o2)]
            }}
        """)

    def _is_root_helper_fn(self) -> None: 
        self.data += textwrap.dedent(f"""
            #[inline]
            pub fn is_root(obj: KnownObject) -> bool {{
                obj == OBJECTS[0].name
            }}
        """)
        
    def _is_independent_helper_fn(self) -> None: 
        self.data += textwrap.dedent(f"""
            #[inline]
            pub const fn is_independent(obj: KnownObject) -> bool {{
                INDEPENDENTS[idx(obj)]
            }}
        """)
    
    def _get_root_obj(self) -> Object: 
        return self.objects[1]
    
    def _build_valid_parents_matrix(self) -> list[list[bool]]:
        """Build matrix where [parent_idx][child_idx] = True if parent can be a parent of child"""
        # This is just the transpose of valid_children, but with different semantics
        n = len(self.objects)
        matrix = [[False] * n for _ in range(n)]
        
        obj_to_idx = {obj.name: i for i, obj in enumerate(self.objects)}
        
        def traverse(obj: "Object", parent_idx=None):
            obj_idx = obj_to_idx[obj.name]
            
            if parent_idx is not None:
                matrix[parent_idx][obj_idx] = True
            
            if hasattr(obj, 'children') and obj.children:
                for child in obj.children:
                    deref_child = child() 
                    if deref_child is None: 
                        raise RuntimeError("Attempted to dereference a child object that doesn't exist!")
                    
                    traverse(deref_child, obj_idx)
        
        traverse(self.objects[1])
        return matrix
    
    def _build_valid_pairs_matrix(self) -> list[list[bool]]:
        """Build matrix where [obj1_idx][obj2_idx] = True if obj1 and obj2 form a pair"""
        n = len(self.objects)
        matrix = [[False] * n for _ in range(n)]
        
        obj_to_idx = {obj.name: i for i, obj in enumerate(self.objects)}
        
        def traverse(obj):
            if hasattr(obj, 'pair') and obj.pair:
                obj_idx = obj_to_idx[obj.name]
                # Find the pair object by name
                for other_obj in self.objects:
                    if other_obj.name == obj.pair:
                        other_idx = obj_to_idx[other_obj.name]
                        matrix[obj_idx][other_idx] = True
                        break
            
            if hasattr(obj, 'children') and obj.children:
                for child in obj.children:
                    deref_child = child() 
                    if deref_child is None: 
                        raise RuntimeError("Attempted to ")
                            
                    traverse(child)
        
        traverse(self.objects[1])
        return matrix
    
    def _build_independents_array(self) -> list[bool]:
        """Build array where each index corresponds to a KnownObject, 
        marking whether it's an independent/organizational object."""
        
        return [obj.is_organizational for obj in self.objects]
    
    def _format_array(self, array: list[bool], array_name: str) -> str:
        """Format a boolean array as Rust constant declaration"""
        
        lines = []
        for i, val in enumerate(array):
            obj_name = self.objects[i].name.upper()
            val_str = "true" if val else "false"
            lines.append(f"    {val_str}, // {obj_name}")
        
        all_lines = "\n".join(lines)
        return f"const {array_name}: [bool; OBJECT_COUNT as usize] = [\n{all_lines}\n];"
    
    def _format_matrix_rows(self, matrix: list[list[bool]], matrix_name: str) -> str:
        """Format a boolean matrix as Rust constant declaration"""
        
        rows = []
        for i, row in enumerate(matrix):
            obj_name = self.objects[i].name.upper()
            bool_str = ", ".join("true" if val else "false" for val in row)
            rows.append(f"    // {matrix_name.replace('_', ' ').title()}: {obj_name}")
            rows.append(f"    [{bool_str}],")
        
        all_rows = "\n".join(rows)
        return f"const {matrix_name}: TableMatrix = [\n{all_rows}\n];"
    
    def _build_valid_children_matrix(self) -> list[list[bool]]:
        """Build matrix where [parent_idx][child_idx] = True if child can be a child of parent"""
        n = len(self.objects)
        matrix = [[False] * n for _ in range(n)]
        
        # Build object name to index mapping
        obj_to_idx = {obj.name: i for i, obj in enumerate(self.objects)}
        
        def traverse(obj: Object, parent_idx=None):
            obj_idx = obj_to_idx[obj.name]
            
            # If this object has a parent, mark the relationship
            if parent_idx is not None:
                matrix[parent_idx][obj_idx] = True
            
            # Recursively traverse children
            if hasattr(obj, 'children') and obj.children:
                for child in obj.children:
                    child_deref = child() 
                    if child_deref is None: 
                        raise RuntimeError("Attempted to traverse on nullptr")
                    
                    traverse(child_deref, obj_idx)
        
        # Start traversal from root
        traverse(self.objects[1])
        return matrix