import os 
import subprocess
import re 
import shutil
from pathlib import Path 
from typing import Any
from globals import OBJECTS, EXPECTED_CLASSIFY_FUNCTIONS, EXPECTED_EXTRACT_FUNCTIONS
from cmake import CMAKE_BIN_DIR
from dataclasses import dataclass

CLASSIFIER_BUILD_ROOT = Path(__file__).parent.parent / "build" 
CLASSIFIER_INCLUDE_ROOT = CLASSIFIER_BUILD_ROOT / "include"  
SHARED_HEADER_PATH = CLASSIFIER_INCLUDE_ROOT / "shared"
CLASSIFIER_GENERATED_INCLUDE_PATH = CLASSIFIER_INCLUDE_ROOT / "generated"  
GENERIC_TEMPLATES_PATH = Path(__file__).parent / "templates"
GENERATED_RS_MODULE_PATH = Path(__file__).parent.parent / "src" / "generated"
@dataclass
class FuncSyntax: 
    return_type: str 
    param_types: list[str]
    
    def __init__(self, return_type: str, param_types: list[str]): 
        self.return_type = return_type 
        self.param_types = param_types

EXPECTED_CLASSIFY_FUNC_SYNTAX = FuncSyntax("Result*", ["fz_context*", "fz_document*"])
EXPECTED_EXTRACT_FUNC_SYNTAX = FuncSyntax("Result*", ["fz_context*", "fz_document*", "void*"])
class Builder: 
    build_dir: Path
    user_cmake_lists_path: Path
    user_build_args: Any
    
    def __init__(self, cmake_lists_path: Path, build_dir: Path,  **kwargs) -> None:
        if cmake_lists_path.name != "CMakeLists.txt": 
            raise RuntimeError("Path provided did not point to a CMakeLists.txt file.")

        self.user_cmake_lists_path = cmake_lists_path
        self.user_build_args = kwargs
        self.build_dir = build_dir
        build_dir.mkdir(exist_ok=True)                

    def build(self) -> None: 
        self._build_mupdf()
        self._generate_module_rs_file()
        self._serialize_object_names_into_enum_rs_module()
        self._serialize_object_names_into_enum_header()
        self._serialize_object_hierarchy_into_rs_module()
        self._serialize_result_header()
        self._validate_expected_funcs_exist() 
        self._copy_generic_headers()
        self._generate_map_header()
        self._build_user_project()
    
    def _generate_module_rs_file(self) -> None: 
        GENERATED_RS_MODULE_PATH.mkdir(exist_ok=True, parents=True)
        mod_rs_path = GENERATED_RS_MODULE_PATH / "mod.rs"

        data = """
pub mod reflected_objects;
pub mod generated_object_types;"""
    
        with open(mod_rs_path, "w") as f: 
            f.write(data)
    
    def _serialize_object_hierarchy_into_rs_module(self) -> None: 
        global OBJECTS
        global SHARED_HEADER_PATH
        
        module_path = GENERATED_RS_MODULE_PATH / "reflected_objects.rs"

        root = OBJECTS[0]
                
        data: str = f""" 
// This module was generated by the build.py script apart of pdf_classifier

#[allow(unused)]
pub struct Node {{
    pub name: &'static str,
    pub children: &'static [Node],
    pub pair: Option<&'static str>,
}}

#[allow(unused)]
pub const OBJECTS: [Node; 1] = [
    {root.__serialize_to_cpp_str__()}
];
"""
        with open(module_path, "w") as f: 
            f.write(data)
    
    def _serialize_result_header(self) -> None: 
        path = SHARED_HEADER_PATH / "result.h"
        data = """
#pragma once 
#include <string>

struct Result
{
private:
    Result(void *p, void (*d)(void *))
    {
        this->type = OK;
        this->payload = p;
        this->deleter = d;
    }
    Result(std::string s)
    {
        this->type = FAIL;
        this->fail_rsn = std::move(s);
    }

public:
    enum Type
    {
        OK,
        FAIL
    } type;
    void *payload;
    std::string fail_rsn;
    void (*deleter)(void *);
    Result(const Result &) = delete;
    Result &operator=(const Result &) = delete;
    Result(Result &&) = delete;
    Result &operator=(Result &&) = delete;
    static Result *ok(void *p, void (*d)(void *)) { return new Result(p, d); }
    static Result *fail(std::string s) { return new Result(s); }
};
"""
        with open(path, "w") as f: 
            f.write(data); 
    
    def _serialize_object_names_into_enum_rs_module(self) -> None: 
        module_path = GENERATED_RS_MODULE_PATH / "generated_object_types.rs"
        
        module_path.parent.mkdir(exist_ok=True, parents=True)
        
        to_str_cases = "\n            ".join(
           f'KnownObject::{object.name.upper()} => "{object.name}".to_string(),' 
           for object in OBJECTS
        )

        from_str_cases = "\n            ".join(
            f'"{object.name}" => KnownObject::{object.name.upper()},'
            for object in OBJECTS
        )
        
        data = f"""
pub enum KnownObject {{
    {", ".join(object.name.upper() for object in OBJECTS)}
}}

impl ToString for KnownObject {{
    fn to_string(&self) -> String {{
        match self {{
            {to_str_cases}
        }}
    }}
}}

impl From<&str> for KnownObject {{
    fn from(value: &str) -> Self {{
        match value {{
            {from_str_cases}
            _ => panic!(
                "Attempted to match {{}} into a KnownObject, but no object corresponds with said string!",
                value
            ),
        }}
    }}
}}
"""
        with open(module_path, "w") as f: 
            written = f.write(data)
            
            if written <= 0: 
                raise RuntimeError("Failed to write data to file.")
            
    def _serialize_object_names_into_enum_header(self) -> None: 
            path = SHARED_HEADER_PATH / "generated_page_types.h"
            
            path.parent.mkdir(exist_ok=True, parents=True)
            
            to_str_cases = "\n        ".join(
                f'case KnownObject::{object.name}: return "{object.name}";'
                for object in OBJECTS
            )
            
            from_str_cases = "\n    ".join(
                f'if(obj == "{object.name}") {{ return KnownObject::{object.name};}}'
                for object in OBJECTS
            )
            
            data = f"""
    #pragma once 

    #include <string> 
    #include <stdexcept>

    enum KnownObject {{ 
        {", ".join(object.name for object in OBJECTS)}
    }};

    std::string page_type_to_string(KnownObject obj) {{
        switch (obj) {{
            {to_str_cases}
            default: return "unknown"; 
        }}
    }}

    KnownObject page_type_from_string(std::string obj) {{
        {from_str_cases}
        throw std::runtime_error("Attempted to convert string to object that doesn't exist!"); 
    }}
    """
            with open(path, "w") as f: 
                written = f.write(data)
                
                if written <= 0: 
                    raise RuntimeError("Failed to write data to file.")
     
    def _get_available_functions(self) -> list[dict[str, Any]]:
        """
        Extracts function declarations from C++ header files in the user's project.
        Returns function name, parameters, and return types.
        """
        functions = []
        project_dir = self.user_cmake_lists_path.parent

        
        # Matches: return_type function_name(params);
        func_pattern = r'((?:\w+::)*\w+\s*[\*&]?)\s+(\w+)\s*\((.*?)\)\s*;'
        param_pattern = r'((?:const\s+)?(?:\w+::)*\w+(?:\s*\*|\s*&)?)\s+(\w+)'
        
        for header_file in project_dir.glob('*.h*'):            
            with open(header_file, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
                
                matches = re.finditer(func_pattern, content)
                for match in matches:
                    return_type, func_name, params_str = match.groups()
                    
                    parameters: list[dict[str, str]] = []
                    if params_str.strip() and params_str.strip() != 'void':
                        for param in params_str.split(','):
                            param_match = re.search(param_pattern, param.strip())
                            if param_match:
                                param_type, param_name = param_match.groups()
                                parameters.append({
                                    'name': param_name,
                                    'type': param_type.strip()
                                })
                    
                    functions.append({
                        'name': func_name,
                        'return_type': return_type.strip(),
                        'parameters': parameters,
                        'file': str(header_file.absolute())
                    })
        
        print(f"Found {functions.__len__()} funcs")
        return functions
        
    def _validate_expected_funcs_exist(self) -> None: 
        global EXPECTED_CLASSIFY_FUNCTIONS
        global EXPECTED_EXTRACT_FUNCTIONS
        
        funcs = self._get_available_functions() 
        
        classify_found = 0
        extract_found = 0 
        for func in funcs: 
            print(func)
            
            if self._validate_classify_func(func): 
                classify_found += 1
        
            if self._validate_extract_func(func):             
                extract_found += 1
        
        print(f"Found {classify_found} classify, {extract_found} extract")        
        #                        func name
        if classify_found != len({item[2] for item in EXPECTED_CLASSIFY_FUNCTIONS}): 
            raise RuntimeError(f"Expected {EXPECTED_CLASSIFY_FUNCTIONS.__len__()} classify functions, but found {classify_found}")

        if extract_found != len({item[2] for item in EXPECTED_EXTRACT_FUNCTIONS}): 
            raise RuntimeError(f"Expected {EXPECTED_EXTRACT_FUNCTIONS.__len__()} extract functions, but found {extract_found}")    
    
    def _validate_classify_func(self, func: dict[str, Any]) -> bool:         
        return self._validate_func(func, EXPECTED_CLASSIFY_FUNCTIONS, EXPECTED_CLASSIFY_FUNC_SYNTAX)
    
    def _validate_extract_func(self, func: dict[str, Any]) -> bool: 
        return self._validate_func(func, EXPECTED_EXTRACT_FUNCTIONS, EXPECTED_EXTRACT_FUNC_SYNTAX)
                 
    def _validate_func(self, func: dict[str, Any], expected_list: list[tuple[str, str, str]], 
                       expected_func_syntax: FuncSyntax) -> bool: 
        given_name: str = func["name"]
        given_return_type: str = func["return_type"]
        given_params: list[dict[str, str]] = func["parameters"]

        for expected_func in expected_list: 
            extracted_name = expected_func[2]

            if given_name != extracted_name: 
                print(f"name wasn't {expected_func[2]}")
                continue
            
            if given_return_type != expected_func_syntax.return_type: 
                print(f"return type wasn't Result*")
                continue
            
            if given_params.__len__() != expected_func_syntax.param_types.__len__(): 
                print("too many params")
                continue
            
            if not self._validate_func_param_types(["fz_context*", "fz_document*"], given_params): 
                print("Func param types were incorrect")
                continue 
            
            return True 
        
        return False 
    
    #                                                     # type                          # name type 
    def _validate_func_param_types(self, expected_types: list[str], given_params: list[dict[str, str]]) -> bool: 
        for expected_type, given_param in zip(expected_types, given_params): 
            given_type: str = given_param["type"] 
            
            if expected_type != given_type:
                return False 
        
        return True                
    
    def _build_user_project(self) -> None: 
        global CMAKE_BIN_DIR
        
        self.user_build_args["BUILD_SHARED_LIBS"] = "OFF"
        self.user_build_args["CLASSIFIER_INCLUDE_DIR"] = str(SHARED_HEADER_PATH)
        self.user_build_args["mupdf_DIR"] = CLASSIFIER_BUILD_ROOT / "lib" / "cmake" / "mupdf"
        self.user_build_args["CMAKE_INSTALL_PREFIX"] = str(CLASSIFIER_BUILD_ROOT)
        self.build_dir.mkdir(exist_ok=True, parents=True)
        
        # configuration
        config_cmd = [os.path.join(CMAKE_BIN_DIR, "cmake")]
        for key, value in self.user_build_args.items():
            config_cmd.append(f"-D{key}={value}")
        config_cmd.append(str(self.user_cmake_lists_path.parent))
        
        subprocess.run(config_cmd, cwd=str(self.build_dir), check=True)
        
        # build 
        build_cmd = [os.path.join(CMAKE_BIN_DIR, "cmake"), "--build", str(self.build_dir), "--config Release"]
        subprocess.run(build_cmd, check=True)
    
        # install headers
        install_cmd = [os.path.join(CMAKE_BIN_DIR, "cmake"), "--install", str(self.build_dir), "--prefix", str(CLASSIFIER_INCLUDE_ROOT.parent)]
        subprocess.run(install_cmd, check=True)
    
    def _copy_generic_headers(self) -> None: 
        global GENERIC_TEMPLATES_PATH
        HEADERS_PATH = GENERIC_TEMPLATES_PATH / "headers" 
        
        for file in os.listdir(HEADERS_PATH): 
            path = HEADERS_PATH / file 
            
            if path.is_file(): 
                shutil.copy2(path, SHARED_HEADER_PATH / file)
                
    def _generate_map_header(self) -> None: 
        global EXPECTED_CLASSIFY_FUNCTIONS
        global EXPECTED_EXTRACT_FUNCTIONS

        all_expected_funcs = EXPECTED_CLASSIFY_FUNCTIONS + EXPECTED_EXTRACT_FUNCTIONS
        
        classify_func_entries = "\n    ".join(
            f'{{ "{func[1]}",  &{func[2]}}},'
            for func in EXPECTED_CLASSIFY_FUNCTIONS
        )
         
        extract_func_entries = "\n    ".join(
            f'{{ "{func[1]}",  &{func[2]}}},'
            for func in EXPECTED_EXTRACT_FUNCTIONS
        )
                
        include_files = "\n".join(
            f'#include <generated/{func}>'
            for func in set(func[0] for func in all_expected_funcs)
        )

        data: str = f"""
#pragma once

#include <string>
#include <vector> 
{include_files}


struct Func
{{
    std::string obj_name;
    void* ptr; 
}};

static const std::vector<Func> ClassifyFuncMap = {{
    {classify_func_entries}
}};

static const std::vector<Func> ExtractFuncMap = {{
    {extract_func_entries}
}};
"""

        map_header = SHARED_HEADER_PATH / "func_map.h" 
        with open(map_header, "w") as f: 
            f.write(data)
            
    def _build_mupdf(self) -> None:
        """Build MuPDF using the existing install_mupdf.cmake"""
        build_dir = self.build_dir / "mupdf_build"
        build_dir.mkdir(exist_ok=True, parents=True)
        
        if (build_dir / "CMakeCache.txt").exists():
            print(f"MuPDF already built at {build_dir}, skipping...")
            return
        
        temp_cmake = build_dir / "CMakeLists.txt"
        mupdf_cmake = Path(__file__).parent / "cmake" / "install_mupdf.cmake"
        
        cmake_content = f"""
cmake_minimum_required(VERSION 3.12.0)
project(mupdf_build)

set(CMAKE_INSTALL_LIBDIR "lib")
set(CMAKE_INSTALL_INCLUDEDIR "include/mupdf")

include({str(mupdf_cmake).replace("\\", "/")})
"""
        
        with open(temp_cmake, "w") as f:
            f.write(cmake_content)
        
        # Configure
        print('config')
        config_cmd = [
            os.path.join(CMAKE_BIN_DIR, "cmake"),
            f"-DCMAKE_INSTALL_PREFIX={str(CLASSIFIER_BUILD_ROOT)}",
            str(build_dir)
        ]
        subprocess.run(config_cmd, cwd=str(build_dir), check=True)
        
        # Build
        print('build')
        build_cmd = [os.path.join(CMAKE_BIN_DIR, "cmake"), "--build", str(build_dir), "--config Release"]
        subprocess.run(build_cmd, check=True)
        
        print('installing')
        # Install
        install_cmd = [os.path.join(CMAKE_BIN_DIR, "cmake"), "--install", str(build_dir)]
        subprocess.run(install_cmd, check=True)
        
        self._create_mupdf_config()
        
    def _create_mupdf_config(self) -> None:
        """Create mupdfConfig.cmake for find_package() support"""
        cmake_dir = CLASSIFIER_BUILD_ROOT / "lib" / "cmake" / "mupdf"
        cmake_dir.mkdir(exist_ok=True, parents=True)
        
        config_content = """
include(FindPackageHandleStandardArgs)

set(MUPDF_LIBRARIES "${CMAKE_INSTALL_PREFIX}/lib/libmupdf.lib")
set(MUPDF_INCLUDE_DIR "${CMAKE_INSTALL_PREFIX}/include/mupdf")


if(NOT TARGET mupdf::mupdf)
    add_library(mupdf::mupdf STATIC IMPORTED)
    set_target_properties(mupdf::mupdf PROPERTIES
        IMPORTED_LOCATION "${CMAKE_INSTALL_PREFIX}/lib/libmupdf.lib"
        INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/include/mupdf"
    )
endif()

find_package_handle_standard_args(mupdf DEFAULT_MSG
    MUPDF_LIBRARIES MUPDF_INCLUDE_DIR
)

set(mupdf_FOUND TRUE)
"""
        
        config_file = cmake_dir / "mupdfConfig.cmake"
        with open(config_file, "w") as f:
            f.write(config_content)
        
        print(f"wrote mupdfConfig.cmake to {config_file}")
        