import os 
import subprocess
import re 
import shutil
from pathlib import Path 
from typing import Any
from globals import OBJECTS, EXPECTED_CLASSIFY_FUNCTIONS, EXPECTED_EXTRACT_FUNCTIONS
from cmake import CMAKE_BIN_DIR

CLASSIFIER_ROOT = Path(__file__).parent.parent 
CLASSIFIER_INCLUDE_ROOT = CLASSIFIER_ROOT / "include"  
SHARED_HEADER_PATH = CLASSIFIER_INCLUDE_ROOT / "shared"
CLASSIFIER_GENERATED_INCLUDE_PATH = CLASSIFIER_INCLUDE_ROOT / "generated"  
GENERIC_TEMPLATES_PATH = Path(__file__).parent / "templates"

class Builder: 
    build_dir: Path
    user_cmake_lists_path: Path
    user_build_args: Any
    
    def __init__(self, cmake_lists_path: Path, build_dir: Path,  **kwargs) -> None:
        if cmake_lists_path.name != "CMakeLists.txt": 
            raise RuntimeError("Path provided did not point to a CMakeLists.txt file.")

        self.user_cmake_lists_path = cmake_lists_path
        self.user_build_args = kwargs
        self.build_dir = build_dir
        build_dir.mkdir(exist_ok=True)                

    def build(self) -> None: 
        self._build_mupdf()
        self._serialize_object_names_into_enum_header()
        self._serialize_object_hierarchy_into_header()
        self._validate_expected_funcs_exist() 
        self._copy_generic_headers()
        self._generate_map_header()
        self._build_user_project()
            
    def _serialize_object_hierarchy_into_header(self) -> None: 
        global OBJECTS
        global SHARED_HEADER_PATH
        
        SHARED_HEADER_PATH.mkdir(exist_ok=True, parents=True)
        header_path = SHARED_HEADER_PATH / "reflected_objects.h"

        root = OBJECTS[0]
                
        data: str = f""" 
// This header was generated by the build.py script apart of pdf_classifier
// When writing implementation for an object (notably for classification/extraction) 
// Please note that this is generated AFTER your implementation is compiled
// Therefore, don't attempt to include it within said implementation headers.

#pragma once 

#include <string> 
#include <vector> 
#include <optional>

struct Node {{
    std::string name;
    std::vector<Node> children;
    std::optional<std::string> pair;
}};

const static Node obj[] = {{
    {root.__serialize_to_cpp_str__()}
}};

"""
        with open(header_path, "w") as f: 
            f.write(data)
    
    def _serialize_object_names_into_enum_header(self) -> None: 
        path = SHARED_HEADER_PATH / "generated_page_types.h"
        
        path.parent.mkdir(exist_ok=True, parents=True)
        
        to_str_cases = "\n        ".join(
            f'case KnownObject::{object.name}: return "{object.name}";'
            for object in OBJECTS
        )
        
        from_str_cases = "\n    ".join(
            f'if(obj == "{object.name}") {{ return KnownObject::{object.name};}}'
            for object in OBJECTS
        )
        
        data = f"""
#pragma once 

#include <string> 
#include <stdexcept>

enum KnownObject {{ 
    {", ".join(object.name for object in OBJECTS)}
}};

std::string page_type_to_string(KnownObject obj) {{
    switch (obj) {{
        {to_str_cases}
        default: return "unknown"; 
    }}
}}

KnownObject page_type_from_string(std::string obj) {{
    {from_str_cases}
    throw std::runtime_error("Attempted to convert string to object that doesn't exist!"); 
}}
"""
        with open(path, "w") as f: 
            written = f.write(data)
            
            if written <= 0: 
                raise RuntimeError("Failed to write data to file.")
     
    def _get_available_functions(self) -> list[dict[str, Any]]:
        """
        Extracts function declarations from C++ header files in the user's project.
        Returns function name, parameters, and return types.
        """
        functions = []
        project_dir = self.user_cmake_lists_path.parent

        
        # Matches: return_type function_name(params);
        func_pattern = r'((?:\w+::)*\w+\s*[\*&]?)\s+(\w+)\s*\((.*?)\)\s*;'
        param_pattern = r'((?:const\s+)?(?:\w+::)*\w+(?:\s*\*|\s*&)?)\s+(\w+)'
        
        for header_file in project_dir.glob('*.h*'):            
            with open(header_file, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
                
                matches = re.finditer(func_pattern, content)
                for match in matches:
                    return_type, func_name, params_str = match.groups()
                    
                    parameters: list[dict[str, str]] = []
                    if params_str.strip() and params_str.strip() != 'void':
                        for param in params_str.split(','):
                            param_match = re.search(param_pattern, param.strip())
                            if param_match:
                                param_type, param_name = param_match.groups()
                                parameters.append({
                                    'name': param_name,
                                    'type': param_type.strip()
                                })
                    
                    functions.append({
                        'name': func_name,
                        'return_type': return_type.strip(),
                        'parameters': parameters,
                        'file': str(header_file.absolute())
                    })
        
        print(f"Found {functions.__len__()} funcs")
        return functions
        
    def _validate_expected_funcs_exist(self) -> None: 
        global EXPECTED_CLASSIFY_FUNCTIONS
        global EXPECTED_EXTRACT_FUNCTIONS
        
        funcs = self._get_available_functions() 
        
        classify_found = 0
        extract_found = 0 
        for func in funcs: 
            print(func)
            
            for expected_func in EXPECTED_CLASSIFY_FUNCTIONS:
                if self._validate_classify_func(func, expected_func): 
                    classify_found += 1
            
            for expected_func in EXPECTED_EXTRACT_FUNCTIONS: 
                if self._validate_extract_func(func, expected_func):             
                    extract_found += 1
        
        print(f"Found {classify_found} classify, {extract_found} extract")        
        
        if classify_found != EXPECTED_CLASSIFY_FUNCTIONS.__len__(): 
            raise RuntimeError(f"Expected {EXPECTED_CLASSIFY_FUNCTIONS.__len__()} classify functions, but found {classify_found}")

        if extract_found != EXPECTED_EXTRACT_FUNCTIONS.__len__(): 
            raise RuntimeError(f"Expected {EXPECTED_EXTRACT_FUNCTIONS.__len__()} classify functions, but found {extract_found}")
    
    def _validate_classify_func(self, func: dict[str, Any], expected_func: tuple[str, str, str]) -> bool: 
        name = func["name"]
        return_type = func["return_type"]
        params = func["parameters"]

        if name != expected_func[2]: 
            # print(f"name wasn't {expected_func[2]}")
            return False
        
        if return_type != "void*": 
            # print("return type wasn't void*")
            return False
        
        if params.__len__() != 1: 
            # print("too many params")
            return False
        
        if params[0]["type"] != "const PageContext&": 
            # print("first type didnt match context type")
            return False
        
        return True 
    
    def _validate_extract_func(self, func: dict[str, Any], expected_func: tuple[str, str, str]) -> bool: 
        name = func["name"]
        return_type = func["return_type"]
        params = func["parameters"]

        if name != expected_func[2]:  
            # print("name didnt match expected")
            return False
        
        if return_type != "void":
            # print("return type wasn't void") 
            return False 
        
        if params.__len__() != 2: 
            # print("param count didnt match")
            return False
        
        if params[0]["type"] != "const PageContext&": 
            # print("first type didnt match context type")
            return False
        
        if params[1]["type"] != "void*": 
            # print("second arg type wasn't void*")
            return False
        
        return True 
                 
    def _build_user_project(self) -> None: 
        global CMAKE_BIN_DIR
        
        self.user_build_args["BUILD_SHARED_LIBS"] = "OFF"
        self.user_build_args["CLASSIFIER_INCLUDE_DIR"] = str(SHARED_HEADER_PATH)
        self.user_build_args["mupdf_DIR"] = CLASSIFIER_ROOT / "lib" / "cmake" / "mupdf"
        self.user_build_args["CMAKE_INSTALL_PREFIX"] = str(CLASSIFIER_ROOT)
        self.build_dir.mkdir(exist_ok=True, parents=True)
        
        # configuration
        config_cmd = [os.path.join(CMAKE_BIN_DIR, "cmake")]
        for key, value in self.user_build_args.items():
            config_cmd.append(f"-D{key}={value}")
        config_cmd.append(str(self.user_cmake_lists_path.parent))
        
        subprocess.run(config_cmd, cwd=str(self.build_dir), check=True)
        
        # build 
        build_cmd = [os.path.join(CMAKE_BIN_DIR, "cmake"), "--build", str(self.build_dir), "--config Release"]
        subprocess.run(build_cmd, check=True)
    
        # install headers
        install_cmd = [os.path.join(CMAKE_BIN_DIR, "cmake"), "--install", str(self.build_dir), "--prefix", str(CLASSIFIER_INCLUDE_ROOT.parent)]
        subprocess.run(install_cmd, check=True)
    
    def _copy_generic_headers(self) -> None: 
        global GENERIC_TEMPLATES_PATH
        HEADERS_PATH = GENERIC_TEMPLATES_PATH / "headers" 
        
        for file in os.listdir(HEADERS_PATH): 
            path = HEADERS_PATH / file 
            
            if path.is_file(): 
                shutil.copy2(path, SHARED_HEADER_PATH / file)
                
    def _generate_map_header(self) -> None: 
        global EXPECTED_CLASSIFY_FUNCTIONS
        global EXPECTED_EXTRACT_FUNCTIONS

        all_expected_funcs = EXPECTED_CLASSIFY_FUNCTIONS + EXPECTED_EXTRACT_FUNCTIONS
        
        func_entries = "\n    ".join(
            f'{{ "{func[0]}", "{func[1]}", "{func[2]}" }},'
            for func in all_expected_funcs
        )        

        data: str = f"""
#pragma once

#include <string>
#include <vector> 

struct Func
{{
    std::string file_name;
    std::string obj_name;
    std::string func_name;
}};

static const std::vector<Func> FuncMap = {{
    {func_entries}
}}
"""

        map_header = SHARED_HEADER_PATH / "func_map.h" 
        with open(map_header, "w") as f: 
            f.write(data)
            
    def _build_mupdf(self) -> None:
        """Build MuPDF using the existing install_mupdf.cmake"""
        build_dir = self.build_dir / "mupdf_build"
        build_dir.mkdir(exist_ok=True, parents=True)
        
        if (build_dir / "CMakeCache.txt").exists():
            print(f"MuPDF already built at {build_dir}, skipping...")
            return
        
        temp_cmake = build_dir / "CMakeLists.txt"
        mupdf_cmake = Path(__file__).parent / "cmake" / "install_mupdf.cmake"
        
        cmake_content = f"""
cmake_minimum_required(VERSION 3.12.0)
project(mupdf_build)

set(CMAKE_INSTALL_LIBDIR "lib")
set(CMAKE_INSTALL_INCLUDEDIR "include/mupdf")

include({str(mupdf_cmake).replace("\\", "/")})
"""
        
        with open(temp_cmake, "w") as f:
            f.write(cmake_content)
        
        # Configure
        config_cmd = [
            os.path.join(CMAKE_BIN_DIR, "cmake"),
            f"-DCMAKE_INSTALL_PREFIX={str(CLASSIFIER_ROOT)}",
            str(build_dir)
        ]
        subprocess.run(config_cmd, cwd=str(build_dir), check=True)
        
        # Build
        build_cmd = [os.path.join(CMAKE_BIN_DIR, "cmake"), "--build", str(build_dir), "--config Release"]
        subprocess.run(build_cmd, check=True)
        
        # Install
        install_cmd = [os.path.join(CMAKE_BIN_DIR, "cmake"), "--install", str(build_dir)]
        subprocess.run(install_cmd, check=True)
        
        self._create_mupdf_config()
        
    def _create_mupdf_config(self) -> None:
        """Create mupdfConfig.cmake for find_package() support"""
        cmake_dir = CLASSIFIER_ROOT / "lib" / "cmake" / "mupdf"
        cmake_dir.mkdir(exist_ok=True, parents=True)
        
        config_content = """
include(FindPackageHandleStandardArgs)

set(MUPDF_LIBRARIES "${CMAKE_INSTALL_PREFIX}/lib/libmupdf.lib")
set(MUPDF_INCLUDE_DIR "${CMAKE_INSTALL_PREFIX}/include/mupdf")


if(NOT TARGET mupdf::mupdf)
    add_library(mupdf::mupdf STATIC IMPORTED)
    set_target_properties(mupdf::mupdf PROPERTIES
        IMPORTED_LOCATION "${CMAKE_INSTALL_PREFIX}/lib/libmupdf.lib"
        INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/include/mupdf"
    )
endif()

find_package_handle_standard_args(mupdf DEFAULT_MSG
    MUPDF_LIBRARIES MUPDF_INCLUDE_DIR
)

set(mupdf_FOUND TRUE)
"""
        
        config_file = cmake_dir / "mupdfConfig.cmake"
        with open(config_file, "w") as f:
            f.write(config_content)
        